/**
 * Sanity check: every package we benchmark must still be a real, loadable library.
 * Autogenerated from tests/package.json `dependencies` — no hardcoded list.
 *
 *   node validate.js
 *
 * A package "works" if its module graph loads. Browser-only libs that touch DOM
 * globals at import time (window/document) are counted as OK — the code loaded,
 * it just wants a browser. Only missing/broken modules fail the run.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgs = Object.keys(JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf8')).dependencies ?? {});

const BROWSER_GLOBAL =
  /\b(window|document|navigator|self|HTMLElement|customElements|requestAnimationFrame)\b is not defined/;

let failed = 0;
const results = [];

for (const name of pkgs) {
  try {
    await import(name);
    results.push(`✓ ${name} — loads`);
  } catch (err) {
    if (BROWSER_GLOBAL.test(err.message)) {
      results.push(`✓ ${name} — loads (browser-only)`);
    } else {
      failed++;
      results.push(`✗ ${name} — ${err.message.split('\n')[0]}`);
    }
  }
}

console.log(`\nPackage validation (${pkgs.length} benchmarked libraries)\n`);
for (const line of results) console.log('  ' + line);
console.log(`\n${pkgs.length - failed}/${pkgs.length} usable\n`);

if (failed > 0) process.exit(1);
