/**
 * Sanity check: every package we benchmark must still be a real, loadable library.
 * Autogenerated from tests/package.json `dependencies` — no hardcoded list.
 *
 *   node validate.js
 *
 * A package "works" if its module graph loads. Browser-only libs that touch DOM
 * globals at import time (window/document) are counted as OK — the code loaded,
 * it just wants a browser. Only missing/broken modules fail the run.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pathJSON = resolve(here, 'package.json');
const pkgs = Object.keys(JSON.parse(readFileSync(pathJSON, 'utf8')).dependencies ?? {});

if (!pkgs.length) {
  console.error(`Failed to validate> No dependencies found in ${pathJSON}`);
  process.exit(1);
}

const BROWSER_GLOBAL =
  /\b(window|document|navigator|self|HTMLElement|customElements|requestAnimationFrame)\b is not defined/;

let failed = 0;

console.log(`\nPackage validation (${pkgs.length} benchmarked libraries)\n`);
for (let i = 0; i < pkgs.length; i++) {
  const name = pkgs[i];
  process.stdout.write(`  (${i + 1}/${pkgs.length}) ${name} ... `);
  try {
    await import(name);
    console.log('✓ loads');
  } catch (err) {
    if (BROWSER_GLOBAL.test(err.message)) {
      console.log('✓ loads (browser-only)');
    } else {
      failed++;
      console.log(`✗ ${err.message.split('\n')[0]}`);
    }
  }
}

console.log(`\n${pkgs.length - failed}/${pkgs.length} usable\n`);

if (failed > 0) process.exit(1);
